name: SPfB
main: de.braste.SPfB.SPfB
version: 1.5.0 (Spigot 1.11.2)
author: Braste
depend: [Vault]

commands:
 home:
  description: Teleportiert den Spieler zu seinem Homepunkt in der aktuellen Welt.
  usage: <command>
 sethome:
  description: Setzt den Homepunkt des Spielers auf die momentane Position in der aktuellen Welt.
  usage: <command>
  aliases: ['shome']
 spawn:
  description: Teleportiert den Spieler zum Spawnpunkt der aktuellen Welt.
  usage: <command>
 setspawn:
  description: Setzt den Spawnpunkt der aktuellen Welt.
  usage: <command>
 warp:
  description: Teleportiert den Spieler zu dem angegebenen Warppunkt in der aktuellen Welt.
  usage: <command> <warplocation>
 createwarp:
  description: Setzt einen Warppunkt an der momentanen Position in der aktuellen Welt.
  usage: <command>
  aliases: ['cwarp']
 listwarps:
  description: Listet alle Warppunkte der aktuellen Welt auf.
  usage: <command>
  aliases: ['lwarps']
 deletewarp:
  description: Loescht den angegebenen Warppunkt in der aktuellen Welt.
  usage: <command> <warplocation>
  aliases: ['dwarp']
 clearinventory:
  description: Leert das Inventar.
  usage: <command> <main|bar|all>
  aliases: ['ci']
 wp:
  description: Teleportiert den Spieler zum angegebenen Wegpunkt in der aktuellen Welt.
  usage: <command> [player] <waypoint>
 listwp:
  description: Listet alle Wegpunkte des Spielers in der aktuellen Welt auf.
  usage: <command> [player]
  aliases: ['lwp']
 setwp:
  description: Setzt einen neuen Wegpunkt mit dem angegebenen Namen in der aktuellen Welt.
  usage: <command> <name>
  aliases: ['swp']
 deletewp:
  description: Loescht den angegebenen Wegpunkt in der aktuellen Welt
  usage: <command> <waypoint>
  aliases: ['dwp']
 tp:
  description: Teleportiert einen Spieler zu einem anderen Spieler.
  usage: <command> <target|source> [target]
 list:
  description: Listet alle Onlinespieler auf.
  usage: <command>
 broadcast:
  description: Sendet eine Systemnachricht an alle Spieler.
  usage: <command> <message>
  aliases: ['b']
 rift:
  description: Die Zeit ist eine Schleife.
  usage: <command> [time]
 removereg:
  description: Löscht die Registrierung eines Spielers
  usage: <command> [player]
  aliases: ['rreg']
 settargetportal:
  description: Setzt ein Portal als Ziel
  usage: <command> [source] [target]
  aliases: ['setportal']